Models/ChamadoModel.cs
using System.ComponentModel.DataAnnotations;

namespace Chamados.Models
{

    public class ChamadoModel
    {
        public int id { get; set; }

        public string titulo { get; set; }

        public string descricao { get; set; }

        public string? status { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace Chamados.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/ChamadoController.cs
using Chamados.Models;
using Chamados.repositorio;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Chamados.Controllers
{
    public class ChamadoController : Controller
    {
        private readonly IChamadoRepositorio _chamadoRepositorio;
        public ChamadoController(IChamadoRepositorio chamadoRepositorio)
        {
            _chamadoRepositorio= chamadoRepositorio;
        }
        public IActionResult EditChmd()
        {
            return View();
        } public IActionResult ExcluirChmd()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Criar(ChamadoModel chamado) 
        { 
            _chamadoRepositorio.Adicionar(chamado);
            return RedirectToAction("Index","home");
        }

      
    }
}

Controllers/HomeController.cs
using Chamados.Models;
using Chamados.repositorio;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Chamados.Controllers
{
    public class HomeController : Controller
    {
        private readonly IChamadoRepositorio _chamadoRepositorio;
        public HomeController(IChamadoRepositorio chamadoRepositorio)
        {
            _chamadoRepositorio = chamadoRepositorio;
        }

        public IActionResult Index()
        {
            return View();
        } 
        public IActionResult ChmdAberto()
        {
            List<ChamadoModel> chamados = _chamadoRepositorio.BuscarTodos();

            return View(chamados);
            
        }
        public IActionResult ChmdEncerrado()
        {
            return View();
        }

    
    }
}

Views/Chamado/EditChmd.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/Chamado/ExcluirChmd.cshtml
@{
    ViewData["Title"] = "Confirmar Exclusao ";
}

<div class="text-center">
    
    <p><b>DESEJA REALMENTE CONFIRMAR A EXCLUSÃO DESTE CHAMADO?</b> </p>
    <div class="btn-group" role="group" aria-label="Basic mixed styles example">
        <a role="button" class="btn btn-danger" asp-controller="Chamado" asp-action="ExcluirMtd"> APAGAR </a>
        <a role="button" class="btn btn-warning" asp-controller="Home" asp-action="Index"> VOLTAR </a>
        
    </div>
</div>

Views/Home/ChmdAberto.cshtml
@model List<ChamadoModel>
@{
    ViewData["Title"] = "Chamados em Aberto";
}

<div class="text-right">
    
    <p>CHAMADOS EM ABERTO</p>
</div>

<table class="table">
    <thead>
        <tr>
            <th scope="col">TITULO</th>
            <th scope="col">DESCRIÇÃO</th>
            <th scope="col">STATUS</th>
            <th scope="col">AÇÃO</th>
        </tr>
    </thead>
    <tbody>
       @if (Model !=null && Model.Any())
        {
            foreach (ChamadoModel chamado in Model )
            {
                <tr>
                    <td>@chamado.titulo</td>
                    <td>@chamado.descricao</td>
                    <td>CRIADO</td>
                    <td>
                        <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                            <a role="button" class="btn btn-danger"  asp asp-controller="Chamado" asp-action="ExcluirChmd"> Excluir </a>
                            <a role="button" class="btn btn-warning" asp-controller="Chamado" asp-action="EditChmd"> Editar </a>
                        </div>
                    </td>
                </tr>
            }

        }

    </tbody>
</table>

Views/Home/ChmdEncerrado.cshtml
@{
    ViewData["Title"] = "Chamados em Encerrados";
}

<div class="text-right">

    <p>CHAMADOS ENCERRADOS</p>
</div>

Views/Home/Index.cshtml
@model ChamadoModel
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">BEM VINDO USUARIO </h1>
    <p>SISTEMA DE CADASTRADO  E ACOMPANHAMENTO DE CHAMADOS</p>
</div>


<form asp-controller="Chamado" asp-action="Criar" method="post">
    <p>CRIAR NOVO CHAMADO</p>
    <div class="form-group">
        <label for="titulo">Titulo do chamado</label>
        <input type="text"  asp-for="titulo" class="form-control" id="titulo" >
     
    </div>
    <br/>
    <div class="form-group">
        <label for="descricao">Descrição do chamado</label>
        <textarea asp-for="descricao" class="form-control" id="descricao" rows="4"></textarea>
    </div>
    <br/>
    <button type="submit" class="btn btn-primary">Enviar</button>
   
</form>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Chamados</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Chamados.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ChmdAberto">Chamados em Aberto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ChmdEncerrado">Chamados Encerrados</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Cadastro de Chamados
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>